### Import Libraries

# Financial Transaction Risk & Anomaly Intelligence

## Exploratory Data Analysis

This notebook explores the PaySim financial transaction dataset to understand transaction behavior, fraud patterns, data quality, and potential features for machine learning.

In [2]:
import pandas as pd

print(pd.__version__)

2.3.3

### 1. Load Dataset

In [3]:
financial_transaction_data = pd.read_csv("../data/Raw/Financial_transaction.csv")
financial_transaction_data

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0

In [4]:
financial_transaction_data.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0

### 2. Understanding Data

In [5]:
financial_transaction_data.shape

(6362620, 11)

In [6]:
financial_transaction_data.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [7]:
financial_transaction_data.isna().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [8]:
financial_transaction_data.dtypes

step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [9]:
financial_transaction_data.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [10]:
financial_transaction_data["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [11]:
8213/6362620

0.001290820448180152

In [12]:
financial_transaction_data["isFraud"].value_counts(normalize=True) * 100

isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

##### The dataset is not balanced as there is only 0.001% of fraud occurs.

#### II - Does fraud happens equally across all types

In [13]:
financial_transaction_data["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [14]:
financial_transaction_data["type"].value_counts(normalize = True)*100

type
CASH_OUT    35.166331
PAYMENT     33.814608
CASH_IN     21.992261
TRANSFER     8.375622
DEBIT        0.651178
Name: proportion, dtype: float64

In [15]:
pd.crosstab(index=financial_transaction_data["isFraud"],columns=financial_transaction_data['type'])

type     CASH_IN  CASH_OUT  DEBIT  PAYMENT  TRANSFER
isFraud
0        1399284   2233384  41432  2151495    528812
1              0      4116      0        0      4097

In [16]:
financial_transaction_data.groupby(by = 'type')['isFraud'].mean()*100

type
CASH_IN     0.000000
CASH_OUT    0.183955
DEBIT       0.000000
PAYMENT     0.000000
TRANSFER    0.768799
Name: isFraud, dtype: float64

In [17]:
financial_transaction_data.groupby('isFraud')["amount"].agg(["count", "mean", "median", "min", "max"])

           count          mean     median   min          max
isFraud
0        6354407  1.781970e+05   74684.72  0.01  92445516.64
1           8213  1.467967e+06  441423.44  0.00  10000000.00

## Sender Balance Analysis

We compare the sender's balance before and after the transaction to identify differences between legitimate and fraudulent transactions.

In [18]:
financial_transaction_data.groupby("isFraud")[["oldbalanceOrg", "newbalanceOrig"]].mean()

         oldbalanceOrg  newbalanceOrig
isFraud
0         8.328287e+05   855970.228109
1         1.649668e+06   192392.631836

In [25]:
balance_change = financial_transaction_data["oldbalanceOrg"] - financial_transaction_data["newbalanceOrig"]

financial_transaction_data["balance_error"] = balance_change - financial_transaction_data["amount"]

financial_transaction_data["balance_error"].describe()

C:\Users\santh\AppData\Local\Temp\ipykernel_4516\3716672640.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  financial_transaction_data["balance_error"] = balance_change - financial_transaction_data["amount"]

count    6.362620e+06
mean    -2.010925e+05
std      6.066505e+05
min     -9.244552e+07
25%     -2.496411e+05
50%     -6.867726e+04
75%     -2.954230e+03
max      1.000000e-02
Name: balance_error, dtype: float64

In [26]:
financial_transaction_data.groupby("isFraud")["balance_error"].agg(["mean", "median", "min", "max"])

                  mean    median          min           max
isFraud
0       -201338.558109 -69049.31 -92445516.64  1.000000e-02
1        -10692.325265      0.00 -10000000.00  3.725290e-09

### Receiver Balance Analysis

In [27]:
''financial_transaction_data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,...,-0.0,-69431.05,-61159.51,-12401.9,-32702.61,0.0,-0.0,-469112.51,-0.0,balance_error
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,...,-4.547474e-12,-69431.05,-61159.51,-12401.9,-32702.61,1.273293e-11,-3.410605e-13,-469112.51,-3.467449e-12,1.455192e-11
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,...,-4.547474e-12,-69431.05,-61159.51,-12401.9,-32702.61,1.273293e-11,-3.410605e-13,-469112.51,-3.467449e-12,-1.136868e-12
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,...,-4.547474e-12,-69431.05,-61159.51,-12401.9,-32702.61,1.273293e-11,-3.410605e-13,-469112.51,-3.467449e-12,0.000000e+00
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,...,-4.547474e-12,-69431.05,-61159.51,-12401.9,-32702.61,1.273293e-11,-3.410605e-13,-469112.51,-3.467449e-12,0.000000e+00
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,...,-4.547474e-12,-69431.05,-61159.51,-12401.9,-32702.61,1.273293e-11,-3.410605e-13,-469112.51,-3.467449e-12,0.000000e+00

In [29]:
financial_transaction_data["dest_balance_error"]=(financial_transaction_data["newbalanceDest"]-financial_transaction_data["oldbalanceDest"]-financial_transaction_data["amount"])
financial_transaction_data["dest_balance_error"]

0         -9.839640e+03
1         -1.864280e+03
2         -1.810000e+02
3         -2.136300e+04
4         -1.166814e+04
               ...
6362615    0.000000e+00
6362616   -6.311409e+06
6362617   -1.000000e-02
6362618   -8.500025e+05
6362619   -4.656613e-10
Name: dest_balance_error, Length: 6362620, dtype: float64

In [31]:
financial_transaction_data.groupby("isFraud")["dest_balance_error"].agg(["mean", "median", "min", "max"])

                  mean   median          min          max
isFraud
0        -54692.231734 -3500.68 -13191233.98  75885725.63
1       -732509.301069 -2231.46 -10000000.00   8875516.29

### Time Analysis

In [33]:
financial_transaction_data.groupby("isFraud")["step"].agg(["mean", "median", "min", "max"])

               mean  median  min  max
isFraud
0        243.235663   239.0    1  718
1        368.413856   367.0    1  743

In [34]:
financial_transaction_data[financial_transaction_data["isFraud"] == 1]["step"].value_counts().sort_index()

step
1      16
2       8
3       4
4      10
5       6
       ..
739    10
740     6
741    22
742    14
743     8
Name: count, Length: 741, dtype: int64

In [35]:
fraud_rate_by_step = (financial_transaction_data.groupby("step")["isFraud"].mean() * 100)
fraud_rate_by_step.describe()

count    743.000000
mean      43.925264
std       48.956185
min        0.000000
25%        0.074895
50%        1.915709
75%      100.000000
max      100.000000
Name: isFraud, dtype: float64